logging:
  level.org.zalando.logbook: TRACE



server:
  error:
    include-binding-errors: always

filmorate:
  default-top-film-count: 10

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true